# Generated by Django 5.0.4 on 2024-04-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_clientes_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='apelido',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
